### ISSUE TITLE
Error: Cannot find module './privconfig-twitter'

### ISSUE THREAD

**Issue by blackthornecl** [tmwagency/node-twitter-heatmap-sentiment#1]
node index.js

module.js:340
    throw err;
          ^
Error: Cannot find module './privconfig-twitter'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/node-twitter-heatmap-sentiment/config/config.js:21:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Any idea?

**Comment by ashleynolan** [comment]
This is covered in the Readme of the application, 'Creating your API Key'.

You need to rename the example twitter config file found in the /config folder to privconfig-twitter.js adding your Twitter API keys. Then, the application should run as expected.
